---
title: Only Jerkin'
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.onlyjerkin.com
description: Celebrating the spirit of the Caribbean through lip smacking flavours,
  music and all round experience. Look out for the jerk bus as we serve the streets
  of London daily.
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
- ".jekyll-cache"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
- jekyll-mentions
- jekyll-default-layout
- jekyll-include-cache
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Only Jerkin
email: hello@onlyjerkin.com
analytics: UA-120718511-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  instagram: https://www.instagram.com/onlyjerkin/
  facebook: https://www.facebook.com/onlyjerkin/
  twitter: https://twitter.com/onlyjerkin
  mixcloud: https://www.mixcloud.com/ljdawes/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: only-jerkin.imgix.net
menu-file: "/uploads/only-jerkin-menu.pdf"
breakpoints:
  small: 880
  medium: 1024
  large: 1440
  xlarge: 1440
  xxlarge: 1440
breakpoints-contained:
  small: 640
  medium: 1024
  large: 1440
  xlarge: 1440
  xxlarge: 1440
covid-text: Due to government restrictions and to keep our customers and team safe,
  for the time being we are operating click and collect and delivery only.
